# Fichier listant les paramètres du module et leurs valeurs par défaut

AREA_TYPE = ["M10", "M5", "M1", "COM"]
BORNE_TAXON = [1, 5, 10, 15]
BORNE_OBS = [1, 20, 40, 60, 80, 100, 120]
SIMPLIFY_LEVEL = 50

AFFICHER_SYNTHESE_PAR_ANNEE = true
AFFICHER_SYNTHESE_PAR_ENTITE_GEO = true
AFFICHER_SYNTHESE_PAR_RG_TAXO = true
AFFICHER_SYNTHESE_PAR_CA = true
AFFICHER_CONTACT_TAXONS = true

